### ISSUE TITLE
not using Special Use Domain Name "resolver.arpa"

### ISSUE THREAD

**Issue by mglt** [ietf-wg-add/draft-ietf-add-ddr#21]
The used of a generic resolver.arpa breaks the DNS security model and as such should be avoided. In addition, the name does not provide any sort of binding between the IP address of the Unencrypted Resolver (at the DNS level) and there is no indicate the DNS server provides a legitimate - or is answering to the question requested by the Client. One may consider a cascade of resolvers. I believe that using _dns.<ip>.in-addr.arpa is preferred.

**Comment by tfpauly** [comment]
@mglt can you explain how using in-addr.arpa here is better/different than a new SUDN like resolver.arpa?

**Comment by mglt** [comment]
I provided two reasons above 1) it breaks the DNS security model and 2) the receiving resolver cannot check it was the intentional destination.

**Comment by tfpauly** [comment]
I think it actually a desirable property here that we don't specify the address, such as `4.3.2.1.in-addr.arpa.`, for a few reasons:
- A resolver may have multiple addresses, but it's convenient to have one DDR record to return
- It limits the possibility for a client having a private address resolver passing up the answer to an ISP resolver, which the client discovers, and (while it may not trust it), can choose to do something about

**Comment by tfpauly** [comment]
Also, why is this any different than `ipv4only.arpa`?

**Comment by enygren** [comment]
See also [RFC 8880](https://www.rfc-editor.org/rfc/rfc8880.html) for how this gets handled for ipv4only.arpa around DNSSEC and may have text to include if not included already.

**Comment by enygren** [comment]
If a concern is queries leaking into the public DNS, we could explore using an alternate class (eg, CHAOS or more likely something new).  Having a LOCAL class for queries intended to be directed specifically to a resolver might not be horrible.  Many common recursive resolvers won't forward/recurse with non-IN class queries.

**Comment by mstojens** [comment]
> This might prevent CPE->ISP resolver lookups, which may or may not be desirable.

Definitely not desirable. While this scenario is out of scope for DDR, we should not be blocking this scenario. Note that DDR currently says that clients may pursue other auth mechanisms for the SVCB data so that other drafts can address this exact scenario. If we make DDR incompatible such that other drafts have to come up with a different data transmission method, we'll be undoing lots of WG progress.

@mglt while DDR does not use DNSSEC, it does provide assurances that the designation is valid via the TLS handshake (or the inherent assumption that control of the same IP address is equivalent to being the original party). Baking the IP address into the target domain name will make DDR brittle to the 85% problem as well as complicate different/multiple resolver designation.

If you have a different proposal for improving the security model of DDR without making the designation data unusable/unobtainable by clients behind local forwarders, please suggest it via a new issue.
