### ISSUE TITLE
Need for designated resolver ?

### ISSUE THREAD

**Issue by mglt** [ietf-wg-add/draft-ietf-add-ddr#22]
I leave to the co-author to check whether we need to introduce such terminology. To me it seems Encrypted resolver could be used instead of designated resolver. This would simplify the text and from abstract intro it is obvious the encrypted resolver being discovered is the one associated to the unencrypted one.  This is just a comment.

**Comment by tfpauly** [comment]
This terminology was based on working group discussion—what's being discovered here isn't specifically something encrypted, but something that has a particular relationship with the existing resolver. Don't assume that the original resolver is always unencrypted.

**Comment by mglt** [comment]
sure. While reading the document I was questioning the need to introduce this term. I agree that this has been  discussed proposed during discussions in the WG. It was probably necessary at one time my question was do we still need it. Now I must say that the terms appear in the title and in the designation of the protocol which makes this harder top remove it - if ever that was needed. The other way around is to look is whether "encrypted resolver" should not be instead "designated resolver".  Again my opinion is that it is an editorial nits that worth being caught as soon as possible to avoid last minute update.

**Comment by mstojens** [comment]
The reason we have a term that is more specific than "encrypted resolver" to convey the relationship between the unencrypted resolver and the encrypted resolver it is recommending for clients wanting to upgrade to encrypted connections. "Equivalence" was ruled out because that conveys _too_ much about the exact functionality between the two resolvers. "Designated" was chosen because the unencrypted resolver is designating the encrypted resolver when the client asks for an encrypted connection.

**Comment by mglt** [comment]
Thanks for the response and clarification. So theoretically the designated resolver could be encrypted or unencrypted. Without having the text in mind any more, I suspect that we are using encrypted as a (tempting) shortcut for designated. if we really want to keep the two terms, I think that explaining the difference in the beginning of the document would help the reader. I am not willing to extend the discussion on this topic, my point was just to raise a warning, and I trust you handle it the best way.
