### ISSUE TITLE
Is "Authenticated" the right term for the mode?

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-ietf-add-ddr#44]
I don't think that you can consider a resolver to be "authenticated" if all you have is an IP cert for an IP address that you found in an RA/DHCP packet.  That's no better than something that you found on a USB stick in a Walmart car park.

This is a policy statement: a client chooses to use a secured protocol for talking to a discovered resolver on the basis that it couldn't be worse than using an unsecured protocol.  This document claims that ownership over the IP address is strictly better.  That only assumes that the PKI you use to verify that ownership is trustworthy.  Thus, the secured protocol is OK to use.

_Originally posted by @martinthomson in https://github.com/ietf-wg-add/draft-ietf-add-ddr/pull/43#discussion_r741627771_

**Comment by mstojens** [comment]
> That only assumes that the PKI you use to verify that ownership is trustworthy. 

Which in addition doesn't apply to the "opportunistic" method which doesn't use PKI at all and simply relies on the IP address being the same, which is subject to IP header attacks.

@tfpauly maybe it's time we just ripped out the "opportunistic" method altogether and leave it to the same domain as Ben's new doc about "what a client can do if they have SVCB info that DDR rejected". Then DDR doesn't need to differentiate between the two approaches because DDR just covers the main one: when starting with an identity, how can we find the encrypted resolver that can claim that identity? (where identity can be either IP address or resolver name but never both at once).

This would make a re-write to remove "authentication" much easier and would make the scope of DDR cleaner. What do you think? The original reason we included that mode was to help cover some other scenarios, but now that PR11 is in its own document, maybe that is no longer necessary (because it is addressing the 85% problem).

**Comment by tfpauly** [comment]
@mstojens I don't think we should change any functionality here—I see this as a matter of naming only. There are two things the WG agreed upon: check for IP in cert, and share an IP.

The question is editorially what to call these modes:

- "Certificate-validated mode"
- "Shared-address mode"

?

**Comment by tfpauly** [comment]
How about just:

- Validated mode
- Unvalidated mode
