### ISSUE TITLE
SVCB-optional/SVCB-reliant

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-ietf-add-ddr#74]
I think that the answer here is that DDR resolution is SVCB-reliant as defined in the SVCB spec.  Can you make that explicit please?

**Comment by bemasc** [comment]
[Section 8.2 of SVCB-DNS](https://ietf-wg-add.github.io/draft-ietf-add-svcb-dns/draft-ietf-add-svcb-dns.html#section-8.2) says 

> when use of this specification is optional, clients SHOULD switch to SVCB-reliant behavior if SVCB resolution succeeds. Specifications making using of this mapping MAY adjust this fallback behavior to suit their requirements.

It sounds like you're saying that DDR should adopt this without adjustments.  That seems reasonable to me.

**Comment by martinthomson** [comment]
Right.  I sort of assumed that it was SVCB-reliant, but it doesn't *say* that.  Certainly, this is not a case where any deviation from spec is necessary.  (The more of those we have, the better.)

**Comment by tfpauly** [comment]
DDR predates when the reliant and optional terms came about, which is why it wasn’t covered. 

I’m not clear on why anything would need to be said here. Reliant and optional seem to be modes for the client to block on getting SVCB records or falling back and ignoring them if they don’t arrive. 

Discovery based on IP addresses is done with an SVCB query for resolver.arpa, and no other query types are allowed for resolver.arpa. By definition, this only works with SVCB. That doesn’t mean that a client can’t be SVCB optional for its general operation — it just means that if SVCB is blocked or fails, you don’t get to discover the encrypted resolver.

What do we need to say here that would actually benefit things?

**Comment by martinthomson** [comment]
So SVCB-optional doesn't even make sense for this specification.  I was just looking for a nudge in the form of: "The resolver/client uses SVCB in a SVCB-reliant mode."  Just so that there is no confusion.

**Comment by tfpauly** [comment]
Yes, optional doesn’t make sense. But I still think that the entire reliant/optional choice is orthogonal to how DDR works. 

These are the two lines that mention reliant mode in the SVCB spec:

> A client is called "SVCB-optional" if it can connect without the use of ServiceMode records, and "SVCB-reliant" otherwise.

> Accordingly, ECH-capable SVCB-optional clients MUST switch to SVCB-reliant connection establishment if SVCB resolution succeeded (following [Section 3](https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-10.html#client-behavior)) and all alternative endpoints have an "ech" key.

Both of these seem to be about client behavior for connection establishment to a hostname. It’s specifically about connecting.

It doesn’t make sense to connect to resolver.arpa; this is a special purpose SVCB query used for discovery, which can lead to a connection.

I don’t see any requirement from the SVCB spec that protocols that use SVCB need to define themselves as “reliant” or “optional”. Is there something I’m missing there?

**Comment by martinthomson** [comment]
How is this not about connecting from the point at which you feed the name into a SVCB query?  A DDR client is trying to connect to a (secure) resolver.  To that end, it is making a SVCB query.  That it uses "resolver.arpa" doesn't change the overall goal.

**Comment by tfpauly** [comment]
Until a client uses the SVCB query for discovery, it doesn’t know if an encrypted resolver exists that is designated.

I’m not sure if saying a DDR-aware client is “SVCB-reliant” means that it will not use the unencrypted resolver for application queries until it discovers an encrypted resolver (which is not a requirement, obviously, since clients can be allowed to continue using unencrypted DNS if their local policy allows it), or it means that the connection to the discovered encrypted DNS server is SVCB-reliant, which is tautologically true since the existence of said server was only discovered via SVCB. 

If it’s the former, we shouldn’t say it because it’s really about client policy for allowing unencrypted DNS. If it’s the latter, I don’t see the value of adding anything, and I’m not sure it really fits the meaning of “reliant”.

**Comment by bemasc** [comment]
I believe DDR clients' recommended behavior is exactly the behavior recommended in Section 8.2 of SVCB-DNS, quoted above.  It is _initially_ SVCB-optional, and _becomes_ SVCB-reliant once SVCB resolution succeeds.  Specifically: if you _do_ discover an encrypted resolver, and you attempt connection, you SHOULD NOT fall back to unencrypted if that connection fails.  Otherwise, you've added a downgrade vulnerability to attackers on the "transport path" (which may not be the same as the bootstrap-query path).

As this is the default recommendation for SVCB-DNS, I don't think any additional normative language is strictly required.  However, I think a reminder might be appropriate.

This does not address the question of whether to wait for SVCB resolution before issuing any initial queries.  As a practical matter, I don't think we can require that.
